language: generic
jobs:
  include:
    - stage: deploy
deploy:
  provider: s3
  access_key_id: "$S3_ACCESS_KEY"
  secret_access_key: "$S3_SECRET_KEY"
  bucket: "ci.smuggle.us"
  local_dir: public
  endpoint: https://us-east-1.linodeobjects.com
