language: generic
jobs:
  include:
    - stage: deploy-live
      script: ./.ci/deploy.sh
      deploy: &s3
        provider: s3
        access_key_id: "$S3_ACCESS_KEY"
        secret_access_key: "$S3_SECRET_KEY"
        bucket: "ci.smuggle.us"
        local_dir: public
        endpoint: https://us-east-1.linodeobjects.com
    - stage: deploy-pr
      script: ./.ci/deploy-pr.sh

stages:
  - name: deploy-live
    if: branch = master
  - name: deploy-pr
    if: type = pull_request
